#!/usr/bin/env node
// Downloads the calligraphic webfonts used by the card back, subset to only
// the glyphs this app can display, and writes src/fonts/fonts.css.
//
// Run: `node scripts/fetch-fonts.mjs` (needs network; the output is committed,
// so this is only re-run to add glyphs or update a font).
//
// Why subset: a full Japanese font is several MB. Google's CSS API takes a
// `text=` parameter and returns a woff2 containing just those glyphs, which
// takes the three faces from ~10 MB to ~1.5 MB — and because each chunk gets
// its own `unicode-range`, a browser only downloads the file for glyphs it
// actually paints. A level-0 user never fetches the kanji chunks at all.
//
// Licensing: all three are SIL OFL 1.1, which permits redistribution with the
// notice — see src/fonts/OFL.txt and src/fonts/README.md.

import { mkdirSync, writeFileSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { KANA } from "../src/kana.js";
import { KANJI } from "../src/data.js";

const OUT_DIR = resolve(dirname(fileURLToPath(import.meta.url)), "../src/fonts");

// Google serves woff2 only to a UA it recognizes as modern; the default
// curl/node UA gets TTF, which is ~2x the bytes.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

// `kanji: false` is measured, not assumed: asking Slackside One for 223 kanji
// returns a 1.6 KB file (~7 bytes/glyph) — the range is declared but there are
// no outlines behind it. Yuji Syuku returns 99 KB for the same request.
const FONTS = [
  { family: "Yuji Syuku", slug: "yuji-syuku", kanji: true },
  { family: "Slackside One", slug: "slackside-one", kanji: false },
  { family: "Hachi Maru Pop", slug: "hachi-maru-pop", kanji: true },
];

// keep each `text=` well under the ~8 KB practical URL limit (9 bytes per
// percent-encoded character)
const CHUNK = 600;

const chunk = (arr, n) =>
  Array.from({ length: Math.ceil(arr.length / n) }, (_, i) =>
    arr.slice(i * n, (i + 1) * n)
  );

async function faceFor(family, text) {
  const url = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(
    family
  )}&text=${encodeURIComponent(text)}`;
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`${family}: css ${res.status}`);
  const css = await res.text();
  const src = css.match(/src:\s*url\(([^)]+)\)/)?.[1];
  const range = css.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim();
  if (!src) throw new Error(`${family}: no font url in css`);
  const font = await fetch(src, { headers: { "User-Agent": UA } });
  if (!font.ok) throw new Error(`${family}: font ${font.status}`);
  return { bytes: Buffer.from(await font.arrayBuffer()), range };
}

const kana = KANA.map((k) => k.kanji);
const kanji = KANJI.map((k) => k.kanji);

mkdirSync(OUT_DIR, { recursive: true });

const rules = [
  "/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.",
  " * Subset webfonts for the card back's calligraphic row.",
  " * SIL OFL 1.1; see OFL.txt and README.md in this directory. */",
  "",
];
let total = 0;

for (const font of FONTS) {
  const groups = [["kana", [kana]]];
  if (font.kanji) groups.push(["kanji", chunk(kanji, CHUNK)]);

  for (const [label, parts] of groups) {
    for (const [i, part] of parts.entries()) {
      const { bytes, range } = await faceFor(font.family, part.join(""));
      const name = `${font.slug}-${label}${parts.length > 1 ? `-${i + 1}` : ""}.woff2`;
      writeFileSync(join(OUT_DIR, name), bytes);
      total += bytes.length;
      rules.push(
        "@font-face {",
        `  font-family: "${font.family}";`,
        "  font-style: normal;",
        "  font-weight: 400;",
        "  font-display: swap;",
        `  src: url("./${name}") format("woff2");`,
        ...(range ? [`  unicode-range: ${range};`] : []),
        "}",
        ""
      );
      console.log(`  ${name.padEnd(32)} ${(bytes.length / 1024).toFixed(1)} KB`);
    }
  }
}

writeFileSync(join(OUT_DIR, "fonts.css"), rules.join("\n"));
console.log(`\nwrote src/fonts/fonts.css — ${(total / 1024 / 1024).toFixed(2)} MB of woff2`);
